### ISSUE TITLE
Allow alternative placeholders for unknown characters

### ISSUE THREAD

**Issue by epage** [kornelski/deunicode#1]
From the docs

> ///   * Some Unicode characters transliterate to an empty string, either on purpose
> ///     or because `deunicode` does not know about the character.
> ///   * Some Unicode characters are unknown and transliterate to `"[?]"`.

1. It isn't clear when an empty string vs `[?]` is used
2. I might want to do something different here, either detect and report an error to the user, put in my own character, etc.

A limited workaround exists
```rust
let custom_replacement = "?";
"string".chars().map(|c|deunicode_char(c).unwrap_or(custom_replacement)).collect::<String>()
```
but `deunicode` does a lot more than that (spacing logic).

(fork of https://github.com/chowdhurya/rust-unidecode/issues/4)

**Comment by kornelski** [comment]
ok, done in 0a850a813d9bd0d2e08c7ff361702b9391bee9b8
