### ISSUE TITLE
Ugly output for zalgo input

### ISSUE THREAD

**Issue by tv42** [kornelski/deunicode#16]
Zalgo (as in https://en.wikipedia.org/wiki/Zalgo_text) input has unexpected noise in the output.

For example:

```rust
#[test]
fn deunicode_zalgo() {
    assert_eq!(deunicode::deunicode("exam҉ple"), "example");
    assert_eq!(deunicode::deunicode("exam\u{489}ple"), "example");
}
```

```
assertion `left == right` failed
  left: "exam-1-000-000-ple"
 right: "example"
```

Here's a Go library that strips those out successfully: https://github.com/tv42/slug/blob/main/slug.go

**Comment by kornelski** [comment]
These modifiers are not decoration for memes. They have actual meaning in the languages they come from.

**Comment by tv42** [comment]
That's not the point thogh.. "ä" has actual meaning in my native tongue, yet a slugifier rewrites it to "a".

**Comment by kornelski** [comment]
Unicode modifiers are not only for small adjustments of the Latin alphabet.

U+0489 represents a notation used to multiply numbers by a million. It's archaic, but dropping it only for aesthetics of a meme feels like vandalism to me.

**Comment by tv42** [comment]
So, I think the underlying difference here is that when encountering broken combining characters, deunicode chooses to try to translate them into ASCII. That's fine I guess.
