### ISSUE TITLE
Include LICENSE file

### ISSUE THREAD

**Issue by ignatenkobrain** [kornelski/deunicode#3]
This is needed for packaging for Fedora and openSUSE.

Much appreciated, thanks!

**Comment by kornelski** [comment]
There is one already: https://github.com/kornelski/deunicode/blob/master/LICENSE

**Comment by ignatenkobrain** [comment]
Ah, I overlooked it.. It needs to be here too -- https://github.com/kornelski/deunicode/blob/master/Cargo.toml#L11

**Comment by kornelski** [comment]
How important it is to have it as a file? And in the tarball, not the repo?

crates.io only requires license name: https://github.com/kornelski/deunicode/blob/f6bd781f8edc54aa4d2d25915b7af4cc3108e77c/Cargo.toml#L19 so I'm only doing what crates.io requires. This is going to be a problem with all my crates.

Could you read the license name for packaging purposes and get a license file template accordingly?

**Comment by ignatenkobrain** [comment]
We do read license from metadata and use it. But we also need file with a full text license.

https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

> Common licenses that require including their texts with all derivative works include ASL 2.0, EPL, BSD and MIT. Packagers should point out to upstream that by not including a proper full license text, they are making it difficult or impossible for anyone to comply with their desired license terms.

While technically you have it in git repo, that does not help us as a distribution to get it because we use tarball from crates.io for purpose of packaging.
