### ISSUE TITLE
More smaller bugs for Chinese pinyin

### ISSUE THREAD

**Issue by zzy** [kornelski/deunicode#7]
Hi, @kornelski, thank you for great crate.

There are more smaller bugs for Chinese Pinyin:
- "`术 -> shu"`, not "`zhu`", such as "`技术 -> ji shu`", not "`ji zhu`"
- "`价 -> jia`", not "`jie`", such as "`评价 -> ping jia`", not "`ping jie`"
- "`旅 -> lv`", such as "`旅游 -> lv you`"

Thank you.

**Comment by kornelski** [comment]
Fixed. Thanks.

**Comment by zzy** [comment]
@kornelski great, thank you!
