### ISSUE TITLE
More smaller bugs for Chinese pinyin

### ISSUE THREAD

**Issue by zzy** [kornelski/deunicode#8]
Hi, @kornelski, thank you for great crate.

There are more smaller bugs for Chinese Pinyin:

"重" is a polyphone character, with more than one reading. 

- In words: "重构", "重复", "重叠", "重阳", "重新", ... "重" reads "chong"
  - "重构" -> "chong gou"
  - "重复" -> "chong fu"
  - "重叠" -> "chong die"
  - "重阳" -> "chong yang"
  - "重新" -> "chong xin"
  -  ...
- In words: "重心", "重要", "重担", "沉重", "重大", ... "重" reads "zhong"
  - "重心" -> "zhong xin"
  - "重要" -> "zhong yao"
  - "重担" -> "zhong dan"
  - "沉重" -> "chen zhong"
  - "重大" -> "zhong da"
  - "慎重" -> "shen zhong"
  - "尊重" -> "zun zhong"
  -  ...

It seems a litter troublesome ... the phenomenon of polyphone characters in Chinese increases the difficulty of Mandarin TTS ( Text to Speech) system.

Thank you.

**Comment by kornelski** [comment]
Unfortunately, this crate maps 1 Unicode codepoint to 1 ASCII string, and doesn't have any other dictionary or context to work with. I'm unable to fix this case without significantly changing the algorithm.

**Comment by zzy** [comment]
@kornelski I understand, thank you！

**Comment by zzy** [comment]
@kornelski hi, kornelski,

A smaller bugs for Chinese Pinyin:

- "什么" -> "shen me", not "shi yao".

Thank you.

**Comment by kornelski** [comment]
Can I change 什 to always be "shen" and 么 to always be "me"?

**Comment by zzy** [comment]
@kornelski hi, great work.

it is passable, "什 -> shi" and "么 -> yao" are seldom used on ordinary occasions.

> 
> 
> Can I change 什 to always be "shen" and 么 to always be "me"?
